[package]
name = "qfhe"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] # C-compatible dynamic library로 컴파일

[build-dependencies]
bindgen = "0.72.0"


[dependencies]
rand = { version = "0.9.2", features = ["simd_support"] }
rand_distr = { version = "0.5.1", features = ["std_math"] }
