[package]
name = "qfhe"
version = "0.0.2"
edition = "2024"

[toolchain]
channel = "stable"

[lib]
crate-type = ["cdylib"] # C-compatible dynamic library로 컴파일

[build-dependencies]
bindgen = "0.72.0"
cbindgen = "0.29.0"

[dependencies]
rand = "0.9.2"
rand_distr = { version = "0.5.1", features = ["std_math"] }
