/* Auto-generated by cbindgen */

#ifndef QFHE_H
#define QFHE_H

/* Do not edit this file manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define POLYNOMIAL_DEGREE 2048

#define NOISE_STD_DEV 3.2

#define MODULUS_Q 340282366920938463463374607431768211293ull

#define PLAINTEXT_MODULUS (1 << 64)

#define SCALING_FACTOR_DELTA (MODULUS_Q / PLAINTEXT_MODULUS)

/**
 * C에서 사용할 컨텍스트 생성 함수
 */
void *qfhe_context_create(void);

/**
 * C에서 컨텍스트를 안전하게 해제하는 함수
 */
void qfhe_context_destroy(void *context_ptr);

/**
 * 메시지를 암호화하는 FFI 함수
 */
void *qfhe_encrypt(void *context_ptr, uint64_t message);

/**
 * 암호문을 복호화하는 FFI 함수
 */
uint64_t qfhe_decrypt(void *context_ptr, void *ciphertext_ptr);

/**
 * 동형적으로 두 암호문을 더합니다.
 */
void *qfhe_homomorphic_add(void *context_ptr, void *ciphertext1_ptr, void *ciphertext2_ptr);

/**
 * 암호문을 안전하게 해제하는 함수
 */
void qfhe_ciphertext_destroy(void *ciphertext_ptr);

#endif  /* QFHE_H */
